"""Tensor handle abstraction.

A :class:`TensorHandle` is the only object the rest of the runtime sees
when it wants to read tensor data. The handle hides whether the data
lives in an mmap region, a downloaded byte buffer, or a freshly decoded
quantized block. The handle also exposes a deterministic :meth:`view`
that hands the caller a read-only NumPy / bytes view; the actual bytes
are never copied unless the caller explicitly asks for :meth:`materialize`.
"""

from __future__ import annotations

import abc
import mmap
from dataclasses import dataclass
from enum import Enum

import numpy as np

from ..utils.types import TensorMetadata


# ---------------------------------------------------------------------------
# bfloat16 support
# ---------------------------------------------------------------------------
#
# NumPy has no native bfloat16. Almost every modern HuggingFace checkpoint
# ships ``BF16`` weights, so the runtime has to widen them itself. bfloat16
# is just the top 16 bits of an IEEE-754 float32, which makes the
# conversion a shift rather than a decode: read the payload as uint16,
# place it in the high half of a uint32, reinterpret as float32.

BF16_DTYPE = "bfloat16"


def is_bfloat16(dtype: str) -> bool:
    """True when ``dtype`` names bfloat16 in any of the spellings we see."""
    return str(dtype).lower() in ("bfloat16", "bf16")


def bfloat16_to_float32(raw: np.ndarray) -> np.ndarray:
    """Widen a uint16 bfloat16 payload into float32."""
    u16 = np.ascontiguousarray(raw, dtype=np.uint16)
    u32 = u16.astype(np.uint32) << np.uint32(16)
    return u32.view(np.float32)


def storage_dtype(dtype: str) -> np.dtype:
    """NumPy dtype used to *read* ``dtype`` off disk."""
    if is_bfloat16(dtype):
        return np.dtype(np.uint16)
    return np.dtype(dtype)


class HandleSource(str, Enum):
    """Where the bytes backing this handle live."""

    MMAP = "mmap"          # mmap of the source file - zero copy.
    BUFFER = "buffer"      # Plain byte buffer held in RAM.
    REMOTE = "remote"      # Streamed from a remote backend (future).
    SYNTHETIC = "synthetic"  # Generated by a backend (tests, fake models).


@dataclass(slots=True)
class TensorView:
    """A read-only view of a tensor.

    The view is valid until the parent :class:`TensorHandle` is closed
    or the underlying memory region is released by the memory manager.

    Attributes
    ----------
    data : numpy.ndarray | bytes
        Either a NumPy view into the mmap/buffer (zero copy), or the raw
        bytes if no dtype conversion has been performed yet.
    shape : tuple[int, ...]
        Logical shape of the tensor.
    dtype : str
        Format-native dtype string.
    """

    data: np.ndarray | bytes
    shape: tuple[int, ...]
    dtype: str

    @property
    def nbytes(self) -> int:
        if isinstance(self.data, np.ndarray):
            return int(self.data.nbytes)
        return len(self.data)

    def as_numpy(self, *, copy: bool = False) -> np.ndarray:
        """Return the data as a NumPy array.

        ``copy=False`` (the default) returns a view when possible. The
        caller must not mutate the array; doing so would corrupt the
        backing mmap for every other consumer.
        """
        if isinstance(self.data, np.ndarray):
            if copy:
                return self.data.copy()
            return self.data
        # Raw bytes - convert once.
        if is_bfloat16(self.dtype):
            arr = bfloat16_to_float32(np.frombuffer(self.data, dtype=np.uint16))
        else:
            arr = np.frombuffer(self.data, dtype=np.dtype(self.dtype))
        # The buffer's logical shape may not be 1-D, so reshape.
        if arr.size != int(np.prod(self.shape)):
            # Fall back to flat view - caller can reshape themselves.
            return arr
        return arr.reshape(self.shape)


class TensorHandle(abc.ABC):
    """Abstract base class for a tensor accessor.

    Subclasses are responsible for providing a :meth:`view` and a
    :meth:`materialize` method. The base class tracks lightweight
    metadata and lifecycle state.
    """

    __slots__ = ("_metadata", "_closed", "_source")

    def __init__(self, metadata: TensorMetadata, source: HandleSource) -> None:
        self._metadata = metadata
        self._source = source
        self._closed = False

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def metadata(self) -> TensorMetadata:
        return self._metadata

    @property
    def source(self) -> HandleSource:
        return self._source

    @property
    def closed(self) -> bool:
        return self._closed

    @property
    def name(self) -> str:
        return self._metadata.key.name

    @property
    def byte_size(self) -> int:
        return int(self._metadata.byte_size)

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def close(self) -> None:
        """Release any native resources held by this handle.

        Calling :meth:`close` more than once is a no-op. Subclasses
        override :meth:`_close_native` to free mmap regions or buffers.
        """
        if self._closed:
            return
        self._close_native()
        self._closed = True

    def _close_native(self) -> None:
        """Hook for subclasses; default is a no-op."""

    def __enter__(self) -> "TensorHandle":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:  # type: ignore[no-untyped-def]
        self.close()

    def __del__(self) -> None:  # pragma: no cover - best-effort cleanup
        try:
            self.close()
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Data access
    # ------------------------------------------------------------------

    @abc.abstractmethod
    def view(self) -> TensorView:
        """Return a read-only view of the tensor."""

    def materialize(self) -> bytes:
        """Return the raw bytes of the tensor (always copies)."""
        view = self.view()
        if isinstance(view.data, np.ndarray):
            return bytes(view.data.tobytes())
        return bytes(view.data)

    def as_numpy(self, *, copy: bool = False) -> np.ndarray:
        """Convenience wrapper around :meth:`TensorView.as_numpy`."""
        return self.view().as_numpy(copy=copy)


# ---------------------------------------------------------------------------
# Concrete handles
# ---------------------------------------------------------------------------


class MmapTensorHandle(TensorHandle):
    """Handle backed by an mmap slice of the source file."""

    __slots__ = ("_mmap", "_offset", "_dtype", "_shape")

    def __init__(
        self,
        metadata: TensorMetadata,
        mmap_obj: mmap.mmap,
        *,
        offset: int,
    ) -> None:
        super().__init__(metadata, HandleSource.MMAP)
        self._mmap = mmap_obj
        self._offset = int(offset)
        self._dtype = storage_dtype(metadata.dtype)
        self._shape = tuple(metadata.shape)

    def view(self) -> TensorView:
        if self._closed:
            raise RuntimeError(f"Handle {self.name!r} is closed")
        # The mmap object's slice produces a zero-copy view.
        slice_obj = self._mmap[self._offset : self._offset + self.byte_size]
        arr = np.ndarray(
            shape=self._shape,
            dtype=self._dtype,
            buffer=slice_obj,
            order="C",
        )
        arr.flags.writeable = False
        if is_bfloat16(self._metadata.dtype):
            # Widening allocates; bfloat16 cannot be viewed in place.
            return TensorView(
                data=bfloat16_to_float32(arr),
                shape=self._shape,
                dtype="float32",
            )
        return TensorView(data=arr, shape=self._shape, dtype=self._metadata.dtype)

    def materialize(self) -> bytes:
        """Return raw bytes from the mmap region.

        We bypass :meth:`view` for mmap handles because the numpy view
        only exposes ``numel * itemsize`` bytes - the mmap region can
        be longer when the dtype is quantised (the on-disk block size
        differs from the logical element count).
        """
        if self._closed:
            raise RuntimeError(f"Handle {self.name!r} is closed")
        # ``mmap[i:j]`` returns a new mmap slice object; ``bytes()`` of
        # that materialises the requested range into a real byte array.
        return bytes(self._mmap[self._offset : self._offset + self.byte_size])

    def _close_native(self) -> None:
        # Hint the kernel to drop the mmap pages for this region.
        #
        # Without this hint the pages stay in the page cache (and count
        # toward RSS) for the entire process lifetime once they have been
        # touched. The backend keeps the parent mmap alive for the
        # duration of inference, so even ``close()`` on the handle does
        # not unmap the region. For very large models (>= 14B in Q4_K,
        # 27B+, ...) the cumulative page cache can grow past several GB
        # before the model is fully streamed, which is enough to OOM
        # memory-constrained hosts even though the scheduler logically
        # "released" the layer.
        #
        # Trade-off: ``MADV_DONTNEED`` is page-aligned. If two small
        # tensors share a 4 KiB page, the kernel may discard the page
        # for both tensors even though only one was released. The next
        # access of the still-resident tensor re-faults from disk -
        # cheap for layer-sized tensors, measurable for tiny ones.
        # We only call madvise for tensors >= 1 MiB so the alignment
        # cost is bounded.
        if self._mmap is not None and self.byte_size >= 1024 * 1024:
            try:
                madv_dontneed = getattr(mmap, "MADV_DONTNEED", None)
                if madv_dontneed is not None:
                    self._mmap.madvise(madv_dontneed, self._offset, self.byte_size)
            except Exception:
                # madvise is best-effort. If the kernel rejects the
                # hint (some FUSE mounts, exotic filesystems), fall
                # back to the old behaviour - the page stays resident
                # until the backend closes.
                pass
        # We don't own the mmap - the backend closes it. Just drop the ref.
        self._mmap = None  # type: ignore[assignment]


class BufferTensorHandle(TensorHandle):
    """Handle backed by an in-RAM ``bytes`` or ``bytearray`` buffer.

    Used for small tensors, fully-decoded quantized blocks, and as a
    fallback when the host filesystem doesn't support mmap (e.g. some
    FUSE mounts).
    """

    __slots__ = ("_buffer",)

    def __init__(self, metadata: TensorMetadata, buffer: bytes | bytearray) -> None:
        super().__init__(metadata, HandleSource.BUFFER)
        self._buffer = buffer

    def view(self) -> TensorView:
        if self._closed:
            raise RuntimeError(f"Handle {self.name!r} is closed")
        # No copy. ``np.frombuffer`` shares memory with the underlying buffer.
        shape = self._metadata.shape
        raw_dtype = storage_dtype(self._metadata.dtype)
        arr = np.frombuffer(self._buffer, dtype=raw_dtype)
        if arr.size != int(np.prod(shape)):
            return TensorView(data=bytes(self._buffer), shape=shape, dtype=self._metadata.dtype)
        if is_bfloat16(self._metadata.dtype):
            return TensorView(
                data=bfloat16_to_float32(arr).reshape(shape),
                shape=shape,
                dtype="float32",
            )
        return TensorView(data=arr.reshape(shape), shape=shape, dtype=self._metadata.dtype)

    def _close_native(self) -> None:
        self._buffer = b""


__all__ = [
    "BufferTensorHandle",
    "HandleSource",
    "MmapTensorHandle",
    "TensorHandle",
    "TensorView",
]